name: env_label
channels:
  - conda-forge
dependencies:
  - ipykernel
  - pystac
  - python=3.10
  - pip:
    - scikit-learn
    - pystac-client
    - shapely
    - black[jupyter]
    - loguru
    - boto3
    - rasterio
    - pandas
    - geopandas
    - boto3
    - botocore
    - seaborn
    - jinja2